package com.interviewplatform.agents.report;

import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Narrative component of the interview report generated by the LLM.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReportNarrative {

    @NotNull
    private String executiveSummary;
    
    @NotNull
    private List<String> strengths;
    
    @NotNull
    private List<String> improvementAreas;
    
    @NotNull
    private List<String> studyPlan;
    
    @NotNull
    private String hiringNarrative;
}
