package com.interviewplatform.agents.common;

import lombok.Builder;
import lombok.Data;

/**
 * Common result contract for all AI evaluation agents.
 *
 * <p>Contains the raw JSON response from the LLM and a parsed composite score,
 * so the aggregator can work without knowing each agent's specific field names.</p>
 *
 * <p><b>Module:</b> Module 6 — Interview Agent (common infrastructure)</p>
 */
@Data
@Builder
public class AgentResult {

    /** Name of the agent that produced this result (for logging/audit). */
    private String agentName;

    /** Whether the agent call succeeded. */
    private boolean success;

    /** The raw JSON string returned by the LLM (for parsing by each agent). */
    private String rawJson;

    /**
     * Overall score for this agent's dimension (0–100).
     * Populated after the agent parses its own raw JSON.
     */
    private int score;

    /** Human-readable summary paragraph generated by the agent. */
    private String summary;

    /** Generic payload for agents that return complex objects (like QuestionGenerationResult). */
    private Object payload;

    /** Error message if {@code success == false}. */
    private String errorMessage;

    // =========================================================================
    // Factory helpers
    // =========================================================================

    public static AgentResult success(String agentName, String rawJson, int score, String summary) {
        return AgentResult.builder()
                .agentName(agentName)
                .success(true)
                .rawJson(rawJson)
                .score(score)
                .summary(summary)
                .build();
    }

    public static AgentResult success(String agentName, Object payload, int score, String summary) {
        return AgentResult.builder()
                .agentName(agentName)
                .success(true)
                .payload(payload)
                .score(score)
                .summary(summary)
                .build();
    }

    public static AgentResult failure(String agentName, String errorMessage) {
        return AgentResult.builder()
                .agentName(agentName)
                .success(false)
                .score(0)
                .errorMessage(errorMessage)
                .build();
    }
}
